### ISSUE TITLE
wgatools maf-ext

### ISSUE THREAD

**Issue by Miles-TANGsk** [wjwei-handsome/wgatools#25]
Hello, I encountered the following error in wgatools `wgatools maf-ext`

```
CMD: wgatools maf-ext test.maf -r Asag.NC_090028.1:41935445-41935588

thread 'main' panicked at src/parser/maf.rs:209:30:
begin <= end (446 <= 0) when slicing `tggttgttgagttctgttaatcccacaaacgaacattacattttgtatttatatag-attggagagagagaaagggaagaaaggtgaAGG------------AAGCAGAGACCAC--AAGCGAgcctggcacacacacacacacacac---acaaa----------tacaaattAGCATGTTTCAAATAATTGTCCCACAGCTTTCCCAAAAAAGAAAGGtaaggtggggggtgggggttaatGTGCCAGGCGGAT`[...]
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
#maf version=1.6 cmd=maf_extract
```

But when I use [`mafExtractor`](https://github.com/dentearl/mafTools/), it can be executed successfully.
```
CMD: mafExtractor -m test.maf --start 41935445 --stop 41935588 --seq Asag.NC_090028.1

##maf version=1

a score=0 mafExtractor_splicedBlock=true splice_id=717859_0
s Asag.NC_090028.1          41935445  143 +   44317406 AGGCATCTGTCAATAATTGTAGGGAGCTGCACTCACAGCTTTGAAATCTCATTAAGTATGCAGTTATCAGGCATAAAGATCAAAAACATTACTCAACTCCGACAGAATCTTATGGAGGAACATTAATTAGCAACAGGCCCACA
s Aste.JARDYH010000007.1    16622143  143 +  105131555 AGGCATCTGTCAATAATTGTAGGGAGCTGCACTCACAGTTTTGAAATCTCATTAAGTATGCAGTTATCAGGCATAAAGATCAAAAACATTACTCAACTCCGACAGAATCTTATGGAGGAACATTAATTAGCAACAGGcccaca
```

```
CMD: wgatools maf-ext test.maf -r Asag.NC_090028.1:41935445-41935587

#maf version=1.6 cmd=maf_extract
a score=255
s       Asag.NC_090028.1        41935445        142     +       44317406        AGGCATCTGTCAATAATTGTAGGGAGCTGCACTCACAGCTTTGAAATCTCATTAAGTATGCAGTTATCAGGCATAAAGATCAAAAACATTACTCAACTCCGACAGAATCTTATGGAGGAACATTAATTAGCAACAGGCCCAC
s       Aste.JARDYH010000007.1  16622160        142     +       105131555       AGGCATCTGTCAATAATTGTAGGGAGCTGCACTCACAGTTTTGAAATCTCATTAAGTATGCAGTTATCAGGCATAAAGATCAAAAACATTACTCAACTCCGACAGAATCTTATGGAGGAACATTAATTAGCAACAGGcccac
```

Position 41935588 is exactly the last base position of the alignment block, can you help me solve it?

![Image](https://github.com/user-attachments/assets/19d85755-7c47-45e5-9aa2-96f3c48016ff)

Test Data: [test.maf.gz](https://github.com/user-attachments/files/20184667/test.maf.gz)

**Comment by wjwei-handsome** [comment]
Hi @Miles-TANGsk !

I have fixed this issue in the latest commit https://github.com/wjwei-handsome/wgatools/commit/894ae67381445168b47b5626468e170ce48ab1ea 

Best regards,
Wenjie

**Comment by Miles-TANGsk** [comment]
Sorry again for troubling you, I updated wgatools, but when I extracted the new coordinates, an error still occurred.

```
CMD: wgatools maf-ext test2.maf -r Asag.NC_090024.1:30624079-30624133


## cut_start_index: 382
## start_coord: 386
## cut_end_index: 413
## end_coord: 417
## cut_start_index: 0
## start_coord: 2053
## cut_end_index: 22
## end_coord: 22
thread 'main' panicked at src/parser/maf.rs:217:30:
begin <= end (2053 <= 22) when slicing `TAATTATATTGATGTTCATATTATGTAAAATAACTCATTTAATAAAATAGTACTTTGATTTTACAATATCACAGGTCAGATGCTTGGAGAAAATCTGCTTGCAGTACCTCTGTTTT-TTTGCCTTATAAAATCTTATCAAGTGAACTTCTCCCCCAGCCAAAAACTAAGCAGTGTCATTACTCGTAACACCATTGCTGTTAACAGAGTTCATCCTAACGACAACA--TTATTTCTCATTCAACATGCTGCTTGCTT`[...]
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
#maf version=1.6 cmd=maf_extract
a score=255
s       Asag.NC_090024.1        30624079        31      +       249210491       AAATTGGTTCATTCTTAAATTTTTTACAGTT
s       Bpum.JAWDJD010000004.1  32213214        31      -       346992387       AAATTGGTTCATTCTTAAATTTTTTACAGTT
```

```
CMD: mafExtractor -m Asag.Bpum.net.maf --start 30624079 --stop 30624132 --seq Asag.NC_090024.1


##maf version=1

a score=0 mafExtractor_splicedBlock=true splice_id=335793_0
s Asag.NC_090024.1          30624079  31 +  249210491 AAATTGGTTCATTCTTAAATTTTTTACAGTT
s Bpum.JAWDJD010000004.1    32213199  31 -  346992387 AAATTGGTTCATTCTTAAATTTTTTACAGTT

a score=0 mafExtractor_splicedBlock=true splice_id=335794_0
s Asag.NC_090024.1          30624111  22 +  249210491 TAATTATATTGATGTTCATATT
s Bpum.JAWDJD010000004.1    32213231  22 -  346992387 TAATTATATTGAAGTTCATATT
```

[test2.maf.gz](https://github.com/user-attachments/files/20191819/test2.maf.gz)

**Comment by wjwei-handsome** [comment]
Hi @Miles-TANGsk !

Sorry for the oversight in the previous update!

The latest commit should resolve the first issue you encountered:

```bash
❯ wgatools maf-ext test2.maf -r Asag.NC_090024.1:30624079-30624133
#maf version=1.6 cmd=maf_extract
a score=255
s       Asag.NC_090024.1        30624079        31      +       249210491       AAATTGGTTCATTCTTAAATTTTTTACAGTT
s       Bpum.JAWDJD010000004.1  32213214        31      -       346992387       AAATTGGTTCATTCTTAAATTTTTTACAGTT

a score=255
s       Asag.NC_090024.1        30624111        22      +       249210491       TAATTATATTGATGTTCATATT
s       Bpum.JAWDJD010000004.1  32213231        22      -       346992387       TAATTATATTGAAGTTCATATT
```

Regarding the second point, as far as I understand, the start position in the MAF format is 0-based.

https://genome.ucsc.edu/FAQ/FAQformat.html#format5
> start -- The start of the aligning region in the source sequence. This is a zero-based number. 


Therefore, in the example, the sequence `T` in the second record with a start of `30,624,111` actually corresponds to the base at position 30,624,112.

This might not align with the start and end positions you intended.

Best regards,
Wenjie

**Comment by Miles-TANGsk** [comment]
Thanks for your prompt reply, it works well. 

Regarding the second point, I didn't notice that the coordinates extracted by maf-ext were in the form of a bed file, I thought it includes the end of region.
